#!/usr/bin/env python3
"""Markers -> expected-findings.json line numbers -> EXPECTED_FINDINGS.md + README table.

expected-findings.json is the only hand-edited answer key. This script:

1. Finds every `TESTBED <ID>` marker in the tracked (and untracked, non-ignored)
   files. The comment syntax does not matter (`#`, `//`, `<!--`), so the script is
   language-neutral. The plant is the first non-blank line after the marker.
2. Writes that line into `line_start` (and `file_path`) for each entry.
   Entries with `history_only: true` are skipped; their location lives in the
   entry's `history` block and is maintained by seed_history.py.
3. Regenerates EXPECTED_FINDINGS.md and the block between
   <!-- BEGIN PLANT TABLE --> and <!-- END PLANT TABLE --> in README.md.

No secret value is ever written: the answer key holds file + line only.

Usage:
    python scripts/render_answer_key.py           # update JSON + MD + README
    python scripts/render_answer_key.py --check   # exit 1 if anything is stale
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
KEY = REPO / "expected-findings.json"
MARKER = re.compile(r"TESTBED ((?:SAST|SEC|DEP|SAFE)-\d{2})\b")
SKIP = {"plan.md", "TESTBED_SPEC.md", "EXPECTED_FINDINGS.md", "README.md"}
TABLE_BEGIN, TABLE_END = "<!-- BEGIN PLANT TABLE -->", "<!-- END PLANT TABLE -->"


def repo_files():
    out = subprocess.run(["git", "ls-files", "-co", "--exclude-standard"], cwd=REPO,
                         capture_output=True, text=True, check=True).stdout
    return [p for p in out.splitlines() if p and not p.startswith("scripts/") and p not in SKIP]


def find_markers():
    """{id: (file_path, plant_line)} for every marker in the repo."""
    found = {}
    for rel in repo_files():
        path = REPO / rel
        if not path.is_file():
            continue
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            continue
        for idx, line in enumerate(lines):
            match = MARKER.search(line)
            if not match:
                continue
            fid = match.group(1)
            if fid in found:
                raise SystemExit(f"duplicate marker {fid}: {found[fid][0]} and {rel}")
            plant = idx + 1
            while plant < len(lines) and not lines[plant].strip():
                plant += 1
            found[fid] = (rel, plant + 1)
    return found


def engines_cell(entry):
    engines = entry.get("expected_engines") or []
    return ", ".join(engines) if engines else "none (negative control)"


def rules_cell(entry):
    rules = entry.get("rule_ids") or {}
    parts = []
    for engine, rule in rules.items():
        if rule:
            parts.append(f"{engine}: " + ", ".join(rule if isinstance(rule, list) else [rule]))
    return "<br>".join(f"`{p}`" for p in parts) or "-"


def location(entry):
    if entry.get("history_only"):
        hist = entry.get("history") or {}
        return f"`{hist.get('file_path', '?')}` (history only)"
    if entry["finding_type"] == "dependency":
        return f"`{entry['file_path']}` ({entry['package']}=={entry['version']})"
    return f"`{entry['file_path']}:{entry['line_start']}`"


def table(key):
    rows = ["| ID | Kind | Location | Expected engines | Rule IDs | CWE | Cross-engine group |",
            "|---|---|---|---|---|---|---|"]
    for e in key["findings"]:
        rows.append(f"| {e['id']} | {e['finding_type']} | {location(e)} | {engines_cell(e)} | "
                    f"{rules_cell(e)} | {e.get('cwe') or '-'} | {e.get('cross_engine_group') or '-'} |")
    return "\n".join(rows)


def expected_md(key):
    out = [f"# Expected findings — {key['repository']}", "",
           "> Generated by `scripts/render_answer_key.py` from `expected-findings.json`.",
           "> Do not edit by hand. No secret values appear here — file and line only.", "",
           f"Language: **{key['language']}** · advisory data verified "
           f"{key.get('advisory_data_verified', '?')}", "",
           "## Engine expectations", ""]
    for engine, state in key["engine_expectations"].items():
        out.append(f"- **{engine}** ({key['scanners'][engine]}): {state}")
    out += ["", "## Plants and controls", "", table(key), "", "## Notes", ""]
    for e in key["findings"]:
        if e.get("notes"):
            out.append(f"- **{e['id']}** — {e['notes']}")
    for note in key.get("notes", []):
        out.append(f"- {note}")
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    original = KEY.read_text(encoding="utf-8")
    key = json.loads(original)
    markers = find_markers()
    problems = []
    for entry in key["findings"]:
        if entry.get("history_only"):
            continue
        if entry["id"] not in markers:
            problems.append(f"{entry['id']}: no marker found")
            continue
        entry["file_path"], entry["line_start"] = markers[entry["id"]]
    known = {e["id"] for e in key["findings"]}
    problems += [f"{m}: marker with no answer-key entry" for m in markers if m not in known]
    if problems:
        raise SystemExit("\n".join(problems))

    outputs = {KEY: json.dumps(key, indent=2, ensure_ascii=False) + "\n",
               REPO / "EXPECTED_FINDINGS.md": expected_md(key)}
    readme = REPO / "README.md"
    if readme.exists():
        text = readme.read_text(encoding="utf-8")
        if TABLE_BEGIN in text and TABLE_END in text:
            head, rest = text.split(TABLE_BEGIN, 1)
            _, tail = rest.split(TABLE_END, 1)
            outputs[readme] = f"{head}{TABLE_BEGIN}\n{table(key)}\n{TABLE_END}{tail}"

    stale = [p.name for p, body in outputs.items()
             if not p.exists() or p.read_text(encoding="utf-8") != body]
    if args.check:
        print("stale: " + ", ".join(stale) if stale else "answer key up to date")
        sys.exit(1 if stale else 0)
    for path, body in outputs.items():
        path.write_text(body, encoding="utf-8", newline="\n")
    print(f"{len(markers)} markers; updated: {', '.join(stale) or 'nothing'}")


if __name__ == "__main__":
    main()
